version: 2
executorType: machine
stages:
  build:
    workDir: ~/electricitymap
    steps:
      - type: checkout
      - type: shell
        name: Show versions
        command: |
          docker --version
          docker-compose --version
      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "parsers/requirements.txt" }}
      - type: shell
        name: Lint
        command: |
          set -exu
          pip install pylint
          sudo apt-get install libxml2-dev
          pip install -r parsers/requirements.txt
          pylint -E parsers/*.py
          python -m unittest discover parsers/test
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "parsers/requirements.txt" }}
          paths:
            - "~/.cache/pip"
      - type: shell
        name: Build
        command: |
          set -exu
          docker-compose build
          docker-compose run web npm run build-release
      - type: shell
        name: Start environment
        command: |
          set -exu
          docker-compose up -d
          sleep 20
          docker-compose logs web
      - type: shell
        name: Run tests
        command: |
          docker-compose ps
          curl --fail -i http://localhost:8000/
          curl --fail -i http://localhost:8000/v1/co2?countryCode=FR
          curl --fail -i http://localhost:8000/v1/exchanges?countryCode=FR
          curl --fail -i http://localhost:8000/v1/production?countryCode=FR
          curl --fail -i http://localhost:8000/v1/price?countryCode=FR
          curl --fail -i http://localhost:8000/v2/history?countryCode=FR
