version: '3.2'
services:
  mockserver:
    build: mockserver
    ports: ['9000:8000']
    volumes:
      - './mockserver/public:/home/public'
      - './mockserver/server.py:/home/server.py'
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
    command: npm run server-dev
    depends_on: ['mockserver']
    environment:
      - NODE_ENV=development
    ports: ['8000:8000']
    volumes:
      - './web/app:/home/web/app'
      - './web/package.json:/home/web/package.json'
      - './web/public:/home/web/public'
      - './web/server.js:/home/web/server.js'
      - './web/views:/home/web/views'
      - './web/webpack.config.js:/home/web/webpack.config.js'
      - './web/locales:/home/web/locales'
      - './config:/home/config'
