version: '2.2'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=electricitymap.org,www.electricitymap.org,electricitymap.tmrow.co
    image: eu.gcr.io/tmrow-152415/electricitymap_web:production
    mem_limit: 200M
    networks: [default, infrastructure] # required to be able to com' with nginx
    scale: 15
    volumes:
      - /home/shared/electricitymap/static/dist:/home/web/public/dist

networks:
  infrastructure:
    external:
      name: infrastructure_default
